apiVersion: v1
kind: Pod
metadata:
  name: todo
  # namespace: prod
  namespace: default

spec:
  containers:
   - name: prod-containers
     image: n91k16/todoapp
     ports: 
      - containerPort: 80
 

